### ISSUE TITLE
Works only with International Release?

### ISSUE THREAD

**Issue by danka74** [IHTSDO/snomed-boot#1]
Tried this with the Swedish release and it seems it was not designed to handle extensions. Is national releases within scope of this package?
Cheers,
Daniel

**Comment by kaicode** [comment]
Hi Daniel,
Thank you for your question. This library currently only being used for loading the international edition but I would love for others to find a use for it and get some real world testing. When dealing with RF2 files I find myself writing the same code over and over..
In response to your question I have just started a feature branch: [feature-extension-loading](https://github.com/IHTSDO/snomed-boot/tree/feature-extension-loading) and had a first stab at the implementaion. It looks for international files and extension files in the release directory and attempts to load one on top of the other to give the full set. Feel free to give that a test and to contribute any ideas or code fixes! 😄 

This library is currently used by the [snomed query project](https://github.com/IHTSDO/snomed-query-service) which is a Lucene implementation of the Expression Constraint Language. Getting extensions to load would be great.

Cheers,
Kai

**Comment by kaicode** [comment]
That feature branch doesn't filter out the international edition files when looking for extension files. Will adjust shortly.

**Comment by kaicode** [comment]
I've updated that extension file filter now.

**Comment by rorydavidson** [comment]
At the time, tested and works, but is out of sync with master now. It would be useful to merge these changes in so they don't get lost in other snomed-boot development.

**Comment by kaicode** [comment]
Release 1.8.0 has support for Snomed Extensions https://github.com/IHTSDO/snomed-boot/releases/tag/1.8.0
