### ISSUE TITLE
ConceptImpl.java throws IllegalStateException

### ISSUE THREAD

**Issue by waitingmyself** [IHTSDO/snomed-boot#2]
when i test with `LoadingProfile.complete` config to load SnomedCT_RF2Release_INT_20160731 data,
i got an IllegalStateException.
then i found the code in ConceptImpl.java

> private Set<Long> collectParentIds(ConceptImpl concept, Set<Long> ancestors, Stack<Long> stack) {
> 		for (Concept parentInt : concept.parents) {
> 			ConceptImpl parent = (ConceptImpl) parentInt;
> 			final Long parentId = parent.id;
> 			if (stack.contains(parentId)) {
> 				**stack.push(parentId);
> 				throw new IllegalStateException("Ancestor loop detected: " + stack.toString());**
> 			}
> 			ancestors.add(parentId);
> 			stack.push(parentId);
> 			collectParentIds(parent, ancestors, stack);
> 			stack.pop();
> 		}
> 		return ancestors;
> 	}

could you talk about why throws IllegalStateException there?
why not use `continue`?
thanks

**Comment by kaicode** [comment]
Hi there. Thanks for your question. 
When calculating the inferred transitive closure for a concept the code assumes that it's working on classified content without any illegal is-a relationship cycles.
At this point in the code a cycle has been detected in the inferred is-a relationships. This is an invalid state for the ontology which would usually be reported by the reasoner (classifier). The exception is thrown to alert the system of this fact so it can be addressed.
One could argue that reporting relationship cycles is not the concern of this function, perhaps this behaviour could be changed.

**Comment by kaicode** [comment]
Please note I have just discovered and fixed #3 in the develop branch.

**Comment by waitingmyself** [comment]
thanks for your reply,Perhaps I understood the wrong intention of this exception.
i will try agin using the latest data.

**Comment by waitingmyself** [comment]
Finally understand the problem, and sure enough there are some relationship between the inactive and the active relationship between the formation of a cycle. ie:103693007 and 252142004.
So under normal circumstances we should not go to the use of inactivated relationship, and immediately we are still using some of the concept of inactivation.
thanks very much~~~~
